services:
  db:
    image: postgres:16
    container_name: DiplomDB
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
